name: Cleanup Feature 
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Environment details provided in the input"

jobs:
  echo-ref:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the environment
        run: echo "The environment is ${{ inputs.environment }}"

      - name: Echo the ref
        run: echo "The ref is ${{ github.ref }}"

      - name: Echo the event ref
        run: echo "The event ref is ${{ github.event.ref }}"

      - name: Echo the actor
        run: |-
          echo "The actor is ${{ github.actor }}"
          echo "The actor is ${{ github.actor.name }}"
          echo "The actor is ${{ github.actor.id }}"
        
      - name: Test action for renovate bot version updates
        uses: actions/checkout@v2